server:
  port: 10011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.136.160:3306/intellect_recovery
    username: root
    password: 123456
  redis:
    host: 43.142.136.160
    port: 6379
    password: 330787456yazhi
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
